### ISSUE TITLE
Dont show information about new email

### ISSUE THREAD

**Issue by ruisimoes** [deepbadger/Zebra#1]
After the last Zimbra update (8.8.9 GA 3019) "Zebra Tray" connect, show calendar warnings but dont show new emails.

In zimbra log has create the next log:

--------------------------------------------------
2018-08-21 17:12:42,064 INFO  [qtp66233253-11846:https:https://10.3.0.9/service/soap/] [ip=10.3.11.15;port=54658;] SoapEngine - BatchRequest [/service/soap/] contains 3 sub-request(s): SearchRequest,SearchRequest,SearchRequest
2018-08-21 17:12:42,064 INFO  [qtp66233253-11846:https:https://10.3.0.9/service/soap/] [name=xxxxxx@xxxxxxx.pt;mid=80;ip=10.3.11.15;port=54658;soapId=6f9f5ad1;] soap - BatchRequest
2018-08-21 17:12:42,064 WARN  [qtp66233253-11846:https:https://10.3.0.9/service/soap/] [name=xxxxxx@xxxxxxx.pt;mid=80;ip=10.3.11.15;port=54658;soapId=6f9f5ad1;] SoapEngine - handler exception
java.lang.NullPointerException
        at com.zimbra.cs.index.SearchParams.isSortByReadFlag(SearchParams.java:644)
        at com.zimbra.cs.index.SearchParams.parse(SearchParams.java:560)
        at com.zimbra.cs.service.mail.Search.handle(Search.java:88)
        at com.zimbra.soap.SoapEngine.dispatchRequest(SoapEngine.java:643)
        at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:468)
        at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:275)
        at com.zimbra.soap.SoapServlet.doWork(SoapServlet.java:304)
        at com.zimbra.soap.SoapServlet.doPost(SoapServlet.java:214)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at com.zimbra.cs.servlet.ZimbraServlet.service(ZimbraServlet.java:211)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
        at com.zimbra.cs.servlet.CsrfFilter.doFilter(CsrfFilter.java:169)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.RequestStringFilter.doFilter(RequestStringFilter.java:54)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:59)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.ETagHeaderFilter.doFilter(ETagHeaderFilter.java:47)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.ContextPathBasedThreadPoolBalancerFilter.doFilter(ContextPathBasedThreadPoolBalancerFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:116)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.ZimbraInvalidLoginFilter.doFilter(ZimbraInvalidLoginFilter.java:117)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:473)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:318)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:288)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:318)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:437)
        at org.eclipse.jetty.server.handler.DebugHandler.handle(DebugHandler.java:84)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:192)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:748)
2018-08-21 17:12:42,065 INFO  [qtp66233253-11846:https:https://10.3.0.9/service/soap/] [name=xxxxxx@xxxxxxx.pt;mid=80;ip=10.3.11.15;port=54658;soapId=6f9f5ad1;] soap - (batch) SearchRequest elapsed=1
2018-08-21 17:12:42,068 INFO  [qtp66233253-11846:https:https://10.3.0.9/service/soap/] [name=xxxxxx@xxxxxxx.pt;mid=80;ip=10.3.11.15;port=54658;soapId=6f9f5ad1;] soap - (batch) SearchRequest elapsed=3
2018-08-21 17:12:42,069 INFO  [qtp66233253-11846:https:https://10.3.0.9/service/soap/] [name=xxxxxx@xxxxxxx.pt;mid=80;ip=10.3.11.15;port=54658;soapId=6f9f5ad1;] soap - (batch) SearchRequest elapsed=1

**Comment by skylevels** [comment]
Same problem after upgrade zimbra to 8.8.9 GA 3019
many errors from zebra tray:
![default](https://user-images.githubusercontent.com/20441040/44462028-cb4dc700-a61b-11e8-86d7-234c7c53d03d.png)
system failure: 
java.lang.NullPointerExeption
zebra.exe

**Comment by deepbadger** [comment]
made changes, check please new version

**Comment by ruisimoes** [comment]
Where i can find the new version?
